FROM ghcr.io/cirruslabs/flutter:stable AS build

WORKDIR /workspace

COPY pubspec.* ./
RUN flutter pub get

COPY . .

ARG API_BASE_URL=/apptrip-api/api/v1
ARG FLUTTER_BASE_HREF=/apptrip-flutter/

RUN flutter build web --release --base-href=${FLUTTER_BASE_HREF} --dart-define=API_BASE_URL=${API_BASE_URL}

FROM nginx:1.25-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /workspace/build/web /usr/share/nginx/html

EXPOSE 80
